# 游戏名称
name : 杠驹瓣

# 游戏端口
# port : 8888
# ext port 1 : 5555
# ext port 2 : 8000
# ext port 3 : 4000
port : 8888

# 引擎绝对路径
#gse path : ./current/
gse path : ./

# 脚本绝对路径
script path : ./

# 地图配置文件
map file : ini/map.ini
